# Generated by Django 5.0.6 on 2024-08-27 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogApp', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(50)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userCreated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(150)])),
                ('translation', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(150)])),
                ('example', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(150)])),
                ('addInfo', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(150)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fromSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromSet', to='frogApp.set')),
            ],
        ),
    ]
