# Generated by Django 5.0.6 on 2024-09-26 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogApp', '0004_alter_card_addinfo_alter_card_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('addedByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user', to=settings.AUTH_USER_MODEL)),
                ('setStarred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_starred', to='frogApp.set')),
            ],
        ),
    ]
