# Generated by Django 5.0.6 on 2025-03-13 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogApp', '0005_starset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='fromSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_from_set', to='frogApp.set'),
        ),
    ]
