# Generated by Django 5.0.6 on 2024-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pic',
            field=models.URLField(max_length=1000),
        ),
    ]
